name: Feature Request
description: Suggest a new feature or improvement for E-SCPE.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - NeuroKoder3
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it clearly.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of E-SCPE would this affect?
      options:
        - CLI (escpe.exe)
        - Core Library (escpe_core.dll)
        - WinUI Desktop App
        - Ledger / Database
        - Licensing
        - FFI Interface
        - CI / Build
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Nice to have
        - Important
        - Critical / Blocker
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature request.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues or feature requests that cover this.
          required: true
